version: "3.7"
services:
  app:
    image: paulcervov/todo-list-app:latest
    ports:
      - 80:80
    environment:
      PUBLIC_URL: ${APP_URL}
      REACT_APP_API_URL: ${API_URL}
  api:
    image: paulcervov/todo-list-api
    ports:
      - 4000:80
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DB: ${DB_DATABASE}
  db:
    image: mysql:5.7
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
